### ISSUE TITLE
Envio de arquivos

### ISSUE THREAD

**Issue by brunaoalberto** [OpenSourceCommunityBrasil/WBotCE#6]
Estou usando o exemplo e não está fazendo o envio de arquivos.

Estou com o cfe4delphi 119.4.3
estou com os binários e com o wbotce.js
as mensagens funcionam normal, apenas arquivos que não vao

**Comment by romulojn** [comment]
Ainda não está compatível com a versão 119 do cef.

**Comment by brunaoalberto** [comment]
Instalei com a versão 117 e está funcional!!
Obrigado!
